### ISSUE TITLE
Configuration.EnvironmentVariables does not respect dash being removed in the key by Azure App Service.

### ISSUE THREAD

**Issue by kevbite** [dotnet/extensions#1659]
### Describe the bug
When a configuration value is set within Azure App Service with a key that includes a dash (`-`). The `Microsoft.Extensions.Configuration.EnvironmentVariables` is unable to load the configuration due to the dash is removed once passed down to the application.

It seems that when an app setting is created in Azure App Service it removes all dashes (`-`) out of the name when passed down to the environment. This then causes not to be able to pick up this configuration value.

#### Create an Azure Web App (Which is really an App Service 😕)

1. Search on the port for Web  App and click create
![step-1-create-web-app](https://user-images.githubusercontent.com/5544715/57138984-f04e2880-6dab-11e9-9279-37203b02720f.png)

2. Fill in all the information and select a docker image running on Linux
![step-2-create-web-app](https://user-images.githubusercontent.com/5544715/57139037-14116e80-6dac-11e9-9b76-3fe337dceb17.png)

3. Select a quick start docker image
![step-3-create-web-app](https://user-images.githubusercontent.com/5544715/57139059-2390b780-6dac-11e9-8289-6b7e98d36502.png)

4. Review and create the Web App
![step-4-create-web-app](https://user-images.githubusercontent.com/5544715/57139090-36a38780-6dac-11e9-8197-9e4a78591c28.png)

#### Add App Setting with Dash (`-`)

5. Once created, Go to the _Configuration_ page, we'll add an app setting with a dash (`-`)
![step-5-add-application-setting](https://user-images.githubusercontent.com/5544715/57139114-3efbc280-6dac-11e9-9fa6-9a17ece861c6.png)

6. We'll just call ours `With-Dash` and give it a random value of `WithDashValue`
![step-6-add-application-setting](https://user-images.githubusercontent.com/5544715/57139160-5c309100-6dac-11e9-87bb-f576091e1f54.png)

7. Review that our new app setting is there, then click save at the top
![step-7-add-application-setting](https://user-images.githubusercontent.com/5544715/57139181-710d2480-6dac-11e9-948c-e3990c77ad84.png)

#### Checking environment variables that are set

8. Open up Kudu from the _Advanced Tools_ menu
![step-8-open-kudu](https://user-images.githubusercontent.com/5544715/57139291-d103cb00-6dac-11e9-9b9b-e1b1e449b211.png)

9. Click App Setting so we can view the app settings in json format
![step-9-view-app-settings](https://user-images.githubusercontent.com/5544715/57139336-eaa51280-6dac-11e9-93bd-c0c7adf6a531.png)

10. Note that app setting that did have a dash, now has the dash removed
![step-10-view-app-settings](https://user-images.githubusercontent.com/5544715/57139367-00b2d300-6dad-11e9-9f5d-3399472c195e.png)

```json
{
   "deployment_branch":"master",
   "SCM_TRACE_LEVEL":"1",
   "SCM_COMMAND_IDLE_TIMEOUT":"60",
   "SCM_LOGSTREAM_TIMEOUT":"1800",
   "SCM_BUILD_ARGS":"",
   "SCM_GIT_USERNAME":"windowsazure",
   "SCM_GIT_EMAIL":"windowsazure",
   "webpages:Version":"3.0.0.0",
   "webpages:Enabled":"true",
   "webactivator:assembliesToScan":"Kudu.Services.Web",
   "SCM_USE_LIBGIT2SHARP_REPOSITORY":"0",
   "REMOTEDEBUGGINGVERSION":"15.0.28307.222",
   "WEBSITE_SITE_NAME":"1f615c06-7c8e-4a47-b600-f6abe08ae3d3",
   "WEBSITE_AUTH_ENABLED":"False",
   "WEBSITE_AUTH_AUTO_AAD":"False",
   "ScmType":"None",
   "WithDash":"WithDashValue",
   "WEBSITE_AUTH_LOGOUT_PATH":"/.auth/logout"
}
```

11. Check environment variables set by dropping in to bash and running `printenv`
![step-11-bash-printenv](https://user-images.githubusercontent.com/5544715/57139430-2d66ea80-6dad-11e9-9118-76853cc943e8.png)

12. Note that the app setting appears twice, one prefix with `APPSETTING_` and the `-` removed
![step-12-bash-printenv](https://user-images.githubusercontent.com/5544715/57139443-322b9e80-6dad-11e9-8ba9-afd3ea80d1ff.png)

13. And another with just the `-` removed
![step-13-bash-printenv](https://user-images.githubusercontent.com/5544715/57139522-61daa680-6dad-11e9-9bae-5023e3b2c3c8.png)

14. Running the following test when trying to access an app setting with a `-` I'd expect the value to be returned when the environment variable is missing the `-`.

```csharp
[Fact]
public void LoadKeyValuePairsFromAzureEnvironment()
{
    var dict = new Hashtable { {"WithDash", "WithDashValue"} };
    var envConfigSrc = new EnvironmentVariablesConfigurationProvider();

    envConfigSrc.Load(dict);

    Assert.Equal("WithDashValue", envConfigSrc.Get("With-Dash"));
}
```

### Expected behavior
The value to be loaded from the environment variable when we are accessing it using the key with the dash and the environment variable key has the dash removed.

#### Package Version

https://www.nuget.org/packages/Microsoft.Extensions.Configuration.EnvironmentVariables/2.2.4

#### Output of `dotnet --info`

```bash
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-011223
 Commit:    118dd862c8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\

Host (useful for support):
  Version: 3.0.0-preview4-27615-11
  Commit:  ee54d4cbd2

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  3.0.100-preview4-011223 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview4-27613-28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by Tratcher** [comment]
If Azure doesn't support dashes here then why do you continue to use dashes?

**Comment by kevbite** [comment]
Hey @Tratcher,

We are **not** using dashes in **our** code, however, **packages that we depend on** use dashes in their configuration sections, and because we want to be able to configure them from the external app settings then it doesn't currently work.

A well-known package that does this is [Healthcheck-UI](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthCheck) their configuration block looks like the following:
```json
{
  "HealthChecks-UI": {
    "HealthChecks": [ ],
    "Webhooks": [ ],
    "EvaluationTimeOnSeconds": 10,
    "MinimumSecondsBetweenFailureNotifications":60
  }
}
```
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/README.md#configuration

Their name `HealthChecks-UI` is statically set in their package and not configurable like many other packages.

Hence why this is an issue as it's out of our control.

**Comment by jkotalik** [comment]
@kevbite I'm reaching out to the app service folks to figure out why dashes are removed in the first place.

**Comment by kevbite** [comment]
@jkotalik thanks for the update 👍.

I'm guessing that it's because environment variables don't support dashes.

>Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit. 
http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html

**Comment by mderriey** [comment]
@kevbite a bit off topic, but the package supports both the `HealthChecks-UI` and `HealthChecksUI` names for the configuration section.

See https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/7ca5744e10bee910ca1a345e8889cf4cedc6f975/src/HealthChecks.UI/Keys.cs#L7-L8

**Comment by kevbite** [comment]
@mderriey that's great to know 👍, looks like they change it on the [30th June](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/commit/074fb0cad96930081e22eb25b531746608df5b3b#diff-902522b9e2897114bfea3781720448b3). Guessing other people bumped into similar problems. 

It's a shame that other package authorizers have to work around this problem instead of it being fixed at source. 😢

**Comment by harre096** [comment]
I'm having this problem too. I have no problem with the portal appsettings not supporting dashes, but this requirement isn't clear from the UI. Better communication around this expectations would be worthwhile even if the behavior doesn't get changed. It's a very subtle 'feature' to have to work around. :)

**Comment by elmonitoboy** [comment]
Please re-open this issue. Environment variables still do not accept dashes and this limitation should be removed
